### ISSUE TITLE
Add title and description to DBs site in English

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-front#408]
We have today a title and description in Hebrew, but not in English.
We should also have them in English.
Here they are:

Title:
Databases: Images, Name Meanings, Family Trees, Communities | BH

Description:
Search archives of images & videos, last names, family trees, Jewish communities, luminaries & more via the free, open databases of The Museum of The Jewish People

**Comment by Libisch** [comment]
Done. See PR #409

**Comment by OriHoch** [comment]
@nuritgazit @Libisch I assume the goal of this is SEO?
if yes, then it was not fixed..

you can see for example in facebook debugger - 
https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fdbs.bh.org.il%2F

looks like the problem is with how angular works - the properties are not available in the page source, only populated in JS

**Comment by OriHoch** [comment]
@TheGrandVizier FYI

**Comment by nuritgazit** [comment]
Yes, the goal is SEO. Is there a solution?

**Comment by OriHoch** [comment]
yes, there are solutions, need to prioritize and work on it

**Comment by Netush** [comment]
Sharon from SEO claims it is done and OK, but because of what Ori wrote, we are double checking. Now waiting for her final feedback.
